# Generated by Django 4.1 on 2022-08-06 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.IntegerField(default=0, help_text='장면 고유 번호', primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, help_text='장면 이름', max_length=255, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('NextScenes', models.ManyToManyField(blank=True, help_text='다음 장면들', null=True, to='game.scene')),
            ],
        ),
        migrations.CreateModel(
            name='Turning_point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='씬 번호', help_text='제목', max_length=255)),
                ('Question', models.CharField(help_text='질문', max_length=1024)),
                ('Player_Answer', models.CharField(blank=True, help_text='플레이어 응답', max_length=1024, null=True)),
                ('Story_Option', models.IntegerField(blank=True, default=0, help_text='선택지 번호', null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('Scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.scene')),
            ],
        ),
        migrations.CreateModel(
            name='Scene_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='제목', help_text='제목', max_length=255)),
                ('Narrative', models.CharField(blank=True, help_text='내용', max_length=4096, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('Scene', models.ForeignKey(help_text='장면', on_delete=django.db.models.deletion.CASCADE, to='game.scene')),
            ],
        ),
        migrations.CreateModel(
            name='Scene_picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pictures', models.ImageField(blank=True, help_text='삽화', null=True, upload_to='')),
                ('Name', models.CharField(default='씬 번호', help_text='이미지 이름', max_length=255)),
                ('Comment', models.CharField(blank=True, help_text='코멘트', max_length=255, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('Scene', models.ForeignKey(help_text='장면', on_delete=django.db.models.deletion.CASCADE, to='game.scene')),
            ],
        ),
    ]
