# Generated by Django 4.1 on 2022-08-08 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='인물 이름', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='scene',
            name='NextScenes',
        ),
        migrations.AddField(
            model_name='scene',
            name='History',
            field=models.ForeignKey(blank=True, help_text='이전 장면', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_scene', to='game.scene'),
        ),
        migrations.AddField(
            model_name='scene',
            name='NextScene_1',
            field=models.ForeignKey(blank=True, help_text='1번 다음 장면', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_next_scene', to='game.scene'),
        ),
        migrations.AddField(
            model_name='scene',
            name='NextScene_2',
            field=models.ForeignKey(blank=True, help_text='2번 다음 장면', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_next_scene', to='game.scene'),
        ),
        migrations.AddField(
            model_name='scene',
            name='NextScene_3',
            field=models.ForeignKey(blank=True, help_text='3번 다음 장면', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_next_scene', to='game.scene'),
        ),
        migrations.AddField(
            model_name='scene',
            name='NextScene_4',
            field=models.ForeignKey(blank=True, help_text='4번 다음 장면', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forth_next_scene', to='game.scene'),
        ),
    ]
