# Generated by Django 4.1 on 2022-08-08 12:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_character_remove_scene_nextscenes_scene_history_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diverges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='분기점', help_text='분기점 이름', max_length=255)),
                ('Comment', models.CharField(blank=True, help_text='코멘트', max_length=255, null=True)),
                ('Checking_list', models.JSONField(default={'key': 'value'}, help_text="{'1':{'i':{'권총'},'f':{'그것을 알아냈다'},'r':{'제퍼슨':'fear'}},'2':{'fi':{'권총','이것을 알아냈다'},'relation':{'제퍼슨','love'}} }")),
                ('Option', models.IntegerField(blank=True, default=0, help_text='결정된 분기점 번호', null=True)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2022, 8, 8, 12, 2, 46, 369664, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='수집한 증거  이름', max_length=255)),
                ('Comment', models.CharField(blank=True, help_text='수집한 증거 설명', max_length=255, null=True)),
                ('Picture', models.ImageField(blank=True, help_text='이미지 삽화', null=True, upload_to='fact')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2022, 8, 8, 12, 2, 46, 367629, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='아이템 이름', max_length=255)),
                ('Comment', models.CharField(blank=True, help_text='아이템설명', max_length=255, null=True)),
                ('Count', models.IntegerField(default=0, help_text='사용 횟수')),
                ('Max_Count', models.IntegerField(default=9999, help_text='최대 사용 횟수(제한이 있는 경우)')),
                ('Usable', models.BooleanField(default=True, help_text='사용 가능 여부')),
                ('Picture', models.ImageField(blank=True, help_text='이미지 삽화', null=True, upload_to='item')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2022, 8, 8, 12, 2, 46, 368079, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='Question_Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='씬 번호', help_text='제목', max_length=255)),
                ('Question', models.CharField(help_text='질문', max_length=1024)),
                ('Player_Answer', models.CharField(blank=True, help_text='플레이어 응답', max_length=1024, null=True)),
                ('Answer_Number', models.IntegerField(blank=True, default=0, help_text='응답 선택지 번호', null=True)),
                ('Result_list', models.JSONField(default={'key': 'value'}, help_text="{'1':{'f':{'마음을 열었다'},'i':{'편지'},'r':{'제퍼슨':{'fear':-5,'love':20}}} }")),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2022, 8, 8, 12, 2, 46, 369218, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.RemoveField(
            model_name='scene_picture',
            name='Pictures',
        ),
        migrations.AddField(
            model_name='character',
            name='Comment',
            field=models.CharField(blank=True, help_text='인물 설명', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='HP',
            field=models.IntegerField(default=100, help_text='체력'),
        ),
        migrations.AddField(
            model_name='character',
            name='MP',
            field=models.IntegerField(default=100, help_text='정신력'),
        ),
        migrations.AddField(
            model_name='character',
            name='Picture',
            field=models.ImageField(blank=True, help_text='이미지 삽화', null=True, upload_to='characters'),
        ),
        migrations.AddField(
            model_name='character',
            name='Relation',
            field=models.JSONField(default={'key': 'value'}, help_text="예시 {'제퍼슨' : {'fear' : 50 , 'love' : 10}, '나나' : {'fear' : 20, 'love' : 50}}"),
        ),
        migrations.AddField(
            model_name='character',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 8, 12, 2, 46, 367091, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='scene_picture',
            name='Picture',
            field=models.ImageField(blank=True, help_text='삽화', null=True, upload_to='scene'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 8, 12, 2, 46, 348446, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='scene_picture',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 8, 12, 2, 46, 368512, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='scene_text',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 8, 12, 2, 46, 368881, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Turning_point',
        ),
        migrations.AddField(
            model_name='question_answer',
            name='Scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.scene'),
        ),
        migrations.AddField(
            model_name='item',
            name='Owner',
            field=models.ForeignKey(blank=True, help_text='소유주', null=True, on_delete=django.db.models.deletion.CASCADE, to='game.character'),
        ),
        migrations.AddField(
            model_name='item',
            name='Scene',
            field=models.ForeignKey(help_text='어느 장면에서 얻는 아이템인가?', on_delete=django.db.models.deletion.CASCADE, to='game.scene'),
        ),
        migrations.AddField(
            model_name='fact',
            name='Owner',
            field=models.ForeignKey(blank=True, help_text='소유주', null=True, on_delete=django.db.models.deletion.CASCADE, to='game.character'),
        ),
        migrations.AddField(
            model_name='fact',
            name='Scene',
            field=models.ForeignKey(help_text='어느 장면에서 얻는 증거인가?', on_delete=django.db.models.deletion.CASCADE, to='game.scene'),
        ),
        migrations.AddField(
            model_name='diverges',
            name='Scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.scene'),
        ),
    ]
