# Generated by Django 4.1 on 2022-08-08 12:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_diverges_fact_item_question_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='Relation',
            field=models.JSONField(default=dict, help_text="예시 {'제퍼슨' : {'fear' : 50 , 'love' : 10}, '나나' : {'fear' : 20, 'love' : 50}}"),
        ),
        migrations.AlterField(
            model_name='character',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='diverges',
            name='Checking_list',
            field=models.JSONField(default=dict, help_text="{'1':{'i':{'권총'},'f':{'그것을 알아냈다'},'r':{'제퍼슨':'fear'}},'2':{'fi':{'권총','이것을 알아냈다'},'relation':{'제퍼슨','love'}} }"),
        ),
        migrations.AlterField(
            model_name='diverges',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='fact',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='item',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='question_answer',
            name='Result_list',
            field=models.JSONField(default=dict, help_text="{'1':{'f':{'마음을 열었다'},'i':{'편지'},'r':{'제퍼슨':{'fear':-5,'love':20}}} }"),
        ),
        migrations.AlterField(
            model_name='question_answer',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='scene',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='scene_picture',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='scene_text',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
