# Generated by Django 4.1 on 2022-08-09 07:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_character_relation_alter_character_pub_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Face_reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, help_text='파일명', max_length=255, null=True)),
                ('uploadedFile', models.FileField(upload_to='Face')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Response', models.JSONField(default=dict, help_text="{'happy':12.5, 'sad':20}")),
            ],
        ),
        migrations.CreateModel(
            name='Speech_to_Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, help_text='파일명', max_length=255, null=True)),
                ('uploadedFile', models.FileField(upload_to='Speech')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Response', models.JSONField(default=dict, help_text="{'text':'Hi I am'}")),
            ],
        ),
        migrations.CreateModel(
            name='Text_reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, help_text='이름', max_length=255, null=True)),
                ('Text', models.CharField(blank=True, help_text='텍스트', max_length=255, null=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Response', models.JSONField(default=dict, help_text="{'happy':12.5, 'sad':25}")),
            ],
        ),
    ]
