# Generated by Django 4.1 on 2022-08-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_face_reader_speech_to_text_text_reader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face_reader',
            name='Response',
            field=models.JSONField(blank=True, default=dict, help_text="{'happy':12.5, 'sad':20}", null=True),
        ),
        migrations.AlterField(
            model_name='speech_to_text',
            name='Response',
            field=models.JSONField(blank=True, default=dict, help_text="{'text':'Hi I am'}", null=True),
        ),
        migrations.AlterField(
            model_name='text_reader',
            name='Response',
            field=models.JSONField(blank=True, default=dict, help_text="{'happy':12.5, 'sad':25}", null=True),
        ),
    ]
