# Generated by Django 4.1 on 2022-08-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_face_reader_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='Relation',
            field=models.JSONField(default=dict, help_text='{"제퍼슨" : {"fear" : 50, "love" : 10}, "나나" : {"fear" : 20, "love" : 50}}'),
        ),
        migrations.AlterField(
            model_name='diverges',
            name='Checking_list',
            field=models.JSONField(default=dict, help_text='{"1":{"i":["권총","밧줄"],"f":["그것을 알아냈다","저것도 알아냈다"],"r":{"제퍼슨":"fear","나나":"love"}},"2":{"i":["권총"],"f":["이것을 알아냈다"],"r":{"제퍼슨":"love"}} }'),
        ),
        migrations.AlterField(
            model_name='face_reader',
            name='Response',
            field=models.JSONField(blank=True, default=dict, help_text='{"happy":12.5, "sad":20}', null=True),
        ),
        migrations.AlterField(
            model_name='question_answer',
            name='Answer_Number',
            field=models.IntegerField(blank=True, default=0, help_text='AI가 분석한 응답 데이터, optimism : 1, negative : 2, sadness : 3, joy : 4, love : 5, anger : 6, fear : 7, surprise : 8', null=True),
        ),
        migrations.AlterField(
            model_name='question_answer',
            name='Result_list',
            field=models.JSONField(default=dict, help_text='{"1":{"f":{"마음을 열었다"},"i":{"편지"},"r":{"제퍼슨":{"fear":-5,"love":20}}} }'),
        ),
        migrations.AlterField(
            model_name='speech_to_text',
            name='Response',
            field=models.JSONField(blank=True, default=dict, help_text='{"text":"Hi I am"}', null=True),
        ),
        migrations.AlterField(
            model_name='text_reader',
            name='Response',
            field=models.JSONField(blank=True, default=dict, help_text='{"happy":12.5, "sad":25}', null=True),
        ),
    ]
