# Generated by Django 4.1 on 2022-08-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_character_relation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diverges',
            name='Checking_list',
            field=models.JSONField(default=dict, help_text='1,2,3,4 분기를 순서대로 확인하여 가장 먼저 맞는 분기로 진행. 만약 1,2,3이 전부 해당하지 않으면 자동으로 4번 분기로 진행. 작성법 예시 : {"1":{"i":["권총","밧줄"],"f":["그것을 알아냈다","저것도 알아냈다"],"r":[{"제퍼슨":"fear"},{"나나":"love"}] },"2":{"i":["권총"],"f":["이것을 알아냈다"],"r":[{"제퍼슨":"love"}] },  }'),
        ),
        migrations.AlterField(
            model_name='question_answer',
            name='Result_list',
            field=models.JSONField(default=dict, help_text='{"1":{"f":["마음을 열었다"],"i":["편지"],"r":[{"제퍼슨":{"fear":-5,"love":20}}, {"나나":{"fear":5, "love":-10}} ] }, "2" : ~~ }'),
        ),
    ]
