# Generated by Django 4.1 on 2022-08-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_diverges_checking_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene_text',
            name='Narrative',
            field=models.TextField(blank=True, help_text='내용', max_length=8192, null=True),
        ),
    ]
